# SPDX-FileCopyrightText: 2024-present Oori Data <info@oori.dev>
# SPDX-License-Identifier: UNLICENSED
services:
  df_discord:
    build:
      context: .
    image: df_discord
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      DF_API_HOST: ${DF_API_HOST}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DF_GUILD_ID: ${DF_GUILD_ID}
      DF_CHANNEL_ID: ${DF_CHANNEL_ID}
  
  df_map:
    build:
      context: ./map_render
    image: df_map
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
    ports:
      - "9100:9100"  # outie:innie
