# SPDX-FileCopyrightText: 2024-present Oori Data <info@oori.dev>
# SPDX-License-Identifier: UNLICENSED
services:
  df_discord:
    build:
      context: .
      dockerfile: dockerfile
    container_name: df-discord
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      DF_API_HOST: ${DF_API_HOST}
      DF_MAP_RENDERER: http://df_map:9100
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DF_GUILD_ID: ${DF_GUILD_ID}
      DF_CHANNEL_ID: ${DF_CHANNEL_ID}
      WASTELANDER_ROLE: ${WASTELANDER_ROLE}
      ALPHA_ROLE: ${ALPHA_ROLE}
      BETA_ROLE: ${BETA_ROLE}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
  
  df_map:
    build:
      context: .
      dockerfile: map_render/dockerfile
    container_name: df-map
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
    ports:
      - "9100:9100"  # outie:innie
    restart: unless-stopped
