# SPDX-FileCopyrightText: 2024-present Oori Data <info@oori.dev>
# SPDX-License-Identifier: UNLICENSED
services:
  df_discord:
    build:
      context: .
    image: df_discord
    environment:
      DF_API_HOST: ${DF_API_HOST}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
